version: '3.8'

services:
  eureka-server:
    build: ./Eureka-Server-Examen
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  api-gateway:
    build: ./apigateway-Examen
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - eureka-server
    networks:
      - microservices-net

  product-service:
    build: ./Productos-Examen
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/productos
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - eureka-server
      - mongodb
      - localstack
    networks:
      - microservices-net

  order-service:
    build: ./Ordenes-Examen
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/ordenes
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - eureka-server
      - mongodb
      - localstack
    networks:
      - microservices-net

  payment-service:
    build: ./Pagos-Examen
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/pagos
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - eureka-server
      - mongodb
      - localstack
    networks:
      - microservices-net

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - microservices-net

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=logs,cloudwatch
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack-init:/etc/localstack/init/ready.d"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
